name: ci

on: [ push ]

env:
  CI: 'true'

jobs:
  check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name : Setup Amplify
        run: yarn global add @aws-amplify/cli
      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v4
        with:
          path: ./node_modules/
          key: node-modules-${{ matrix.node-version }}-${{ hashFiles('./**/yarn.lock') }}
      - name: Install dependencies
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --non-interactive
      - name: Setup Amplify
        run: amplify pull --appId $(cat ./amplify/team-provider-info.json | jq -r .prod.awscloudformation.AmplifyAppId) --envName dev --yes
      - name: Amplify checkout
        run: amplify env checkout dev
      - name: Type check
        run: yarn type-check
      - name: Linter check
        run: yarn lint
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run tests
        run: yarn test
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.node-version }}
          path: ./playwright-report/
          retention-days: 30
